[workspace]
members = [
    ".",
    "nfm-file-system",
    "nfm-search-core",
    "nfm-search-ffi",
]
resolver = "2"

[package]
name = "nfm-rust-win32host"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_nfm"
crate-type = ["cdylib", "rlib"]

[features]
default = ["skia"]
skia = ["dep:skia-safe"]

[dependencies]
nfm_search_core = { path = "nfm-search-core"}
nfm_file_system = { path = "nfm-file-system"}
anyhow = "1"
crossbeam-channel = "0.5"
rayon = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
skia-safe = { version = "0.97.2", optional = true }
windows = { version = "0.62", features = [
    "Win32_Foundation",
    "Win32_Graphics_Direct2D",
    "Win32_Graphics_Direct2D_Common",
    "Win32_Graphics_DirectWrite",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Gdi",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Com",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_IO",
    "Win32_System_LibraryLoader",
    "Win32_System_Pipes",
    "Win32_System_Threading",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
] }
windows-numerics = "0.3"
